Resolve Typescript Compile Error
With allowJS set to true, we got this error when we tried to compile: "error TS5055: Cannot write file '...20180910231418-initial-migration.js' because it would overwrite input file."

We may want to look at this again in the future, but for the moment, simply disabling the option seems to do the trick.